# yaml syntax: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
whitepaper_journal:
    event: 1qWTjaUDtrAHYKqyu1aZoSR3yVK2LHFEap1WgfgcSX6c
    avatar: 1qGo3opGOS8rdcsr3Fc7j79y_LnWPxNvC
    font: 1giYvAN0_5gs71c9Vj5quHZ2syvKuj-5K
