data:
  font:
    remote: 1giYvAN0_5gs71c9Vj5quHZ2syvKuj-5K
    local: /tmp/abc_apps/fonts/
  template:
    remote: 1gp9k9iDP0eiHPFr2xCfhJpRDvbCnWw5k
    local: /tmp/abc_apps/membership/card/template/
  output:
    local: /tmp/abc_apps/membership/card/output
txt_style:
  name:
    box: [105, 481, 400]
    gap: [2, 0]
    align: left
    font:
      type: arial
      size: 23
    fill: [230, 230, 230, 255] # white
  date:
    box: [870, 478, 1000]
    gap: [0, 0]
    align: left
    font:
      type: arial
      size: 23
    fill: [230, 230, 230, 255] # white
